import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Second from '../components/Second'
import Third from '../components/Third'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Second/>
        <Third/>
      </main>
    </>
  )
}
